image: node:4.2.1
before_script:
  - npm install
  - npm install -g react-native-cli

build:
  script:
    - mkdir build
    - react-native bundle --platform ios --verbose true --assets-dest ./build/assets --sourcemap-output ./build/main.map --bundle-output ./build/main.jsbundle --entry-file index.ios.js